# Generated by Django 6.0.3 on 2026-04-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bienes_inmueble', '0004_tipoenlacesocio_alter_inmuebles_options_and_more'),
        ('app_socios', '0019_alter_socios_apellidos_alter_socios_nombres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmuebles',
            name='nombre',
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='lote',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='manzana',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='codigo_socio_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_socios.codigosasociadossocio'),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='socio_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_socios.socios'),
        ),
    ]
