# Generated by Django 6.0.3 on 2026-04-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bienes_inmueble', '0005_remove_inmuebles_nombre_inmuebles_lote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebles',
            old_name='socio_relacionado',
            new_name='socio_poseedor_actual',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='codigo_socio_asociado',
        ),
    ]
