# Generated by Django 6.0.3 on 2026-04-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bienes_inmueble', '0006_rename_socio_relacionado_inmuebles_socio_poseedor_actual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmuebles',
            options={'ordering': ['manzana']},
        ),
    ]
