# Generated by Django 6.0.3 on 2026-03-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0014_alter_socios_fecha_modificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoFolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'codigo_folio',
            },
        ),
        migrations.AlterField(
            model_name='personasrelacionadassocio',
            name='tipo_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_socios.tipofamiliar'),
        ),
        migrations.AddField(
            model_name='socios',
            name='codigo_folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_socios.codigofolio'),
        ),
    ]
