# Generated by Django 6.0.3 on 2026-03-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0014_alter_socios_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='personasrelacionadassocio',
            name='dni',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personasrelacionadassocio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socios',
            name='codigo_folio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personasrelacionadassocio',
            name='tipo_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_socios.tipofamiliar'),
        ),
    ]
