# Generated by Django 6.0.3 on 2026-03-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0015_personasrelacionadassocio_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosSocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=15)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estados_socio',
            },
        ),
        migrations.AddField(
            model_name='socios',
            name='estado_actual_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_socios.estadossocio'),
        ),
    ]
