# Generated by Django 6.0.3 on 2026-03-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0015_codigofolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personasrelacionadassocio',
            name='dni',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personasrelacionadassocio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
