# Generated by Django 6.0.3 on 2026-03-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0016_estadossocio_socios_estado_actual_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personasrelacionadassocio',
            name='dni',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
