# Generated by Django 6.0.3 on 2026-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0017_alter_personasrelacionadassocio_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='activo_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
