# Generated by Django 6.0.3 on 2026-04-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0018_socios_activo_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='apellidos',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socios',
            name='nombres',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socios',
            name='tipo_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_socios.tiposocio'),
        ),
    ]
