# Generated by Django 6.0.3 on 2026-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0019_alter_socios_apellidos_alter_socios_nombres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personasrelacionadassocio',
            old_name='denominacion',
            new_name='apellidos',
        ),
        migrations.AddField(
            model_name='personasrelacionadassocio',
            name='nombres',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
