# Generated by Django 6.0.3 on 2026-04-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0020_rename_denominacion_personasrelacionadassocio_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personasrelacionadassocio',
            name='es_socio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
