# Generated by Django 6.0.3 on 2026-03-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_bienes_inmueble', '0004_tipoenlacesocio_alter_inmuebles_options_and_more'),
        ('app_socios', '0016_estadossocio_socios_estado_actual_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransferencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=30)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_transferencias',
            },
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_transferencia', models.DateField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bienes_inmueble.inmuebles')),
                ('socio_transferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferente', to='app_socios.socios')),
                ('socio_transferido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferido', to='app_socios.socios')),
            ],
            options={
                'db_table': 'transferencias',
            },
        ),
    ]
