# Generated by Django 6.0.3 on 2026-04-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0019_alter_socios_apellidos_alter_socios_nombres_and_more'),
        ('app_transferencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionPersonasTransferencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_socios.socios')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transferencias.transferencias')),
            ],
            options={
                'db_table': 'relacion_personas_transferencias',
            },
        ),
    ]
