# Generated by Django 6.0.3 on 2026-04-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transferencias', '0002_relacionpersonastransferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencias',
            name='codigo_documento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencias',
            name='codigo_relacionado_transferencia',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencias',
            name='observaciones',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
    ]
