# Generated by Django 6.0.3 on 2026-04-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transferencias', '0003_transferencias_codigo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencias',
            name='tipo_transferencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_transferencias.tipotransferencias'),
            preserve_default=False,
        ),
    ]
