# Generated by Django 6.0.3 on 2026-04-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transferencias', '0004_transferencias_tipo_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencias',
            name='codigo_relacionado_transferencia',
            field=models.CharField(max_length=10),
        ),
    ]
