# Generated by Django 6.0.3 on 2026-04-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bienes_inmueble', '0006_rename_socio_relacionado_inmuebles_socio_poseedor_actual_and_more'),
        ('app_transferencias', '0005_alter_transferencias_codigo_relacionado_transferencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferencias',
            options={'ordering': ['codigo_documento']},
        ),
        migrations.RemoveField(
            model_name='transferencias',
            name='inmueble',
        ),
        migrations.AddField(
            model_name='transferencias',
            name='inmueble_huerto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_huerto', to='app_bienes_inmueble.inmuebles'),
        ),
        migrations.AddField(
            model_name='transferencias',
            name='inmueble_parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_parcela', to='app_bienes_inmueble.inmuebles'),
        ),
    ]
