# Generated by Django 6.0.3 on 2026-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transferencias', '0006_alter_transferencias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencias',
            name='codigo_relacionado_transferencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
