# Generated by Django 6.0.3 on 2026-04-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transferencias', '0007_alter_transferencias_codigo_relacionado_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencias',
            name='observaciones',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
