# Generated by Django 6.0.3 on 2026-04-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transferencias', '0008_alter_transferencias_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTransferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=30)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categoria_transferencia',
            },
        ),
        migrations.AddField(
            model_name='transferencias',
            name='categoria_transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transferencias.categoriatransferencia'),
        ),
    ]
